version: "3"

services:
  login-system-test:
    build: ..
    image: login-system:testing
    container_name: "login-system-testing"
    environment:
      - FLASK_APP=run.py
      - APP_MODE=test
      - PYTHONDONTWRITEBYTECODE=1
      # Filter out SQLAlchemy Deprecation warnings for the time being. There is a pull request to fix
      #   this warning that is currently in the prerelease build of flask-sqlalchemy-3.0.0. Once the
      #   prerelease build becomes stable, we should move to flask-sqlalchemy-3.0.0 and remove this
      #   environment variable
      #
      #   Pull Request: https://github.com/pallets-eco/flask-sqlalchemy/pull/1087
      - PYTHONWARNINGS=ignore::DeprecationWarning
    entrypoint: ["bash", "start_application.sh", "test"]
    networks:
      - login-system-testing-network

networks:
  login-system-testing-network:
